padrino/padrino-docs

guides/home.md
and put Delivering Mail after Admin and Authenticaion as thats the flow of the buttons within the docs themselves
=> Fixed broken link 

guides/generators.md
Modify test options from 'testspec' to 'testunit'
=> modify test options

blog/2016-01-29-new-website.md
@padrino/collaborators is this post okay? If yes, can somebody merge and deploy this post?
=> Add new blog post about website redesign

guides/03_features/01_padrino-admin.html.md
Fixed incorrect spelling of project_module in access control example , re-worded some sentences to flow "better".
=> Update 01_padrino-admin.html.md code and grammar

guides/02_getting-started/03_blog-tutorial.html.md
I've updated the guides and examples. The problem is now, that the sceencast is not up-to-date and I've add notes about this (see the commit <https://github.com/padrino/padrino-docs/commit/b9dfdf078e1ab18e2dac9b2dc6ad1ca57b9c49e4>).
You can see the running app under <https://calm-tor-92217.herokuapp.com/posts>. The problem I've so far, is that on the admin-page <https://calm-tor-92217.herokuapp.com/admin/> the application.css of the admin interface is not there (<view-source:https://calm-tor-92217.herokuapp.com/admin/stylesheets/application.css>) but it works if I run it locally. Think this shouldn't be a problem.
I've updated some links and gists as well. You can read the article under <http://stagingpadrinorb.wikimatze.de/guides/getting-started/blog-tutorial/>
Cheers Matthias
=> Rework blog tutorial

guides/01_introduction/03_examples.html.md
Thanks for asking to add the project. Right now it barely scratches the potential of Sinatra and Padrino. But I hope more will come.
=> Adding getVolunteers to examples

guides/03_features/02_padrino-admin.html.md
Pics can be seen on <http://stagingpadrinorb.wikimatze.de/guides/features/padrino-admin/> - please say if they are fine.
=> Add two images for padrino-admin

blog/2016-05-08-padrino-0-12-6-backport-and-bug-fixes.md, blog/2016-05-09-padrino-0-13-2-project-flag-bug-fixes-and-component-upgrades.md
Blog posts for upcoming 0.12.6 and 0.13.2 releases cc @padrino/collaborators
=> Push drafts for 0.12.6 and 0.13.2 releases

guides/01_introduction/02_why-learn-padrino.html.md, guides/01_introduction/04_the-bleeding-edge.html.md, guides/04_generators/02_projects.html.md, guides/04_generators/10_admin.html.md, guides/05_controllers/02_routing.html.md
I went through a few of the pages and made some grammatical and spelling fixes (one code fix). I believe there were one or two changes in capitalization.
=> Update spelling / grammar / capitalization

guides/01_introduction/03_examples.html.md
=> Add Lumen project under examples

guides/03_features/02_padrino-admin.html.md
My question to @padrino/collaborators is: Has anybody used cassandra in a Padrino/Rails project? Is it worth writing an adapter for it?
=> Cassandra has been replaced with ruby-driver adapter

guides/04_generators/10_admin.html.md
Looks like it was removed some time ago and causing some confusion.
Re: https://github.com/padrino/padrino-framework/issues/2087
=> Remove mention of admin themes

guides/02_getting-started/04_blog-tutorial.html.md
https://github.com/padrino/padrino-framework/issues/2049#issuecomment-229626178
=> added documentation on padrino environment and reload configuration

guides/03_features/03_padrino-mailer.html.md
README says 
> Word wrap must be set to 80
But I ignored this as other lines are greater than 80.
=> Mailer updates for testing and delivery methods

guides/05_controllers/07_prioritized-routes.html.md
Fixes a few 'then' vs. 'than' instances.
=> Fix some typos in Prioritized Routes

guides/03_features/04_padrino-cache.html.md
This PR pulls in https://github.com/padrino/padrino-framework/blob/master/padrino-cache/README.rdoc to update the caching documentation and resolve #124.
=> Updated cache docs

guides/01_introduction/03_examples.html.md
Fixes #126.
As an aside, the site should be published. There have been several updates that are not on padrinorb.com.
=> Updates to Example List

guides/03_features/08_localization.html.md
I know we're a huge people, but we still speak a type of Portuguese :)
=> pt_BR stands for "Brazilian Portuguese", not "Brazilian"

blog/2017-03-20-padrino-0-14-0.html.md
@wikimatze @nesquena @ujifgc  Could you review this?
=> add the cascading section

guides/02_getting-started/04_blog-tutorial.html.md
A few improvements as discussed in #119 
Closes #119
=> Blog tutorial improvements

guides/03_features/02_padrino-admin.html.md
Correctly indent a code sample :)
=> Fix typo in 02_pardino-admin.html.md

guides/01_introduction/03_examples.html.md
As we talked over [Gitter](https://gitter.im/padrino/padrino-framework?at=5af2769e97f07c7e137c6aed)
=> Added tokyo project to Introduction/Examples page

blog/2019-02-01-gitter.html.md, blog/2019-02-04-gitter.html.md
=> Add draft of gitter post

blog/2020-09-13-story-behind-padrino-logo.html.md
Preview of post can be seen under https://stagingpadrinorb.wikimatze.de/blog/story-behind-padrino-logo/
=> Add post about creation of Padrino logo - kudo to Daniel Polo
